<?php

return [
    'hierarchy' => [
        'SUPER-ADMIN' => ['SUPER-ADMIN', 'ADMIN', 'WORKSHOP', 'WAREHOUSE', 'OPERATOR', 'PE', 'STORE', 'PPIC', 'MAINTENANCE', 'SECONDPROCESS', 'ASSEMBLYPROCESS', 'BUSINESS', 'PRODUCTION', 'QUALITY'],
        'ADMIN' => ['ADMIN', 'WORKSHOP', 'WAREHOUSE', 'OPERATOR', 'PE', 'STORE', 'PPIC', 'MAINTENANCE', 'SECONDPROCESS', 'ASSEMBLYPROCESS', 'BUSINESS', 'PRODUCTION', 'QUALITY'],
        'WORKSHOP' => ['WORKSHOP'],
        'WAREHOUSE' => ['WAREHOUSE'],
        'OPERATOR' => ['OPERATOR'],
        'PE' => ['PE'],
        'STORE' => ['STORE'],
        'PPIC' => ['PPIC'],
        'MAINTENANCE' => ['MAINTENANCE'],
        'SECONDPROCESS' => ['SECONDPROCESS'],
        'ASSEMBLYPROCESS' => ['ASSEMBLYPROCESS'],
        'BUSINESS' => ['BUSINESS'],
        'PRODUCTION' => ['PRODUCTION'],
        'QUALITY' => ['QUALITY']
    ],
];
